package user.api;

import org.codehaus.jackson.JsonNode;
import org.codehaus.jackson.annotate.JsonSubTypes;
import org.codehaus.jackson.annotate.JsonTypeInfo;
import org.codehaus.jackson.map.ObjectMapper;
import org.codehaus.jackson.map.ObjectWriter;
import org.codehaus.jackson.node.ObjectNode;
import javax.persistence.*;
import java.util.*;

@Entity
@Table(name = "USER_ACCOUNT")
@Inheritance(strategy=InheritanceType.JOINED)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "userAccountType")
@JsonSubTypes(
        {@JsonSubTypes.Type(value = BasicUserAccount.class, name = "BASIC"),
        @JsonSubTypes.Type(value = StandardUserAccount.class, name = "STANDARD") })
public abstract class UserAccount {

    //region Properties
    @Id
    @GeneratedValue
    private Long id;

    @Enumerated(EnumType.STRING)
    private UserAccountType userAccountType;

    @OneToMany(fetch = FetchType.LAZY, cascade={CascadeType.ALL}, orphanRemoval = true)
    @MapKey(name="id")
    private Map<Long, UserProfile> userProfiles;

    private int userProfilesAmount;

    //endregion

    //region Constructors

    public UserAccount() {

        this.userProfiles = new LinkedHashMap<Long,UserProfile>();
    }

    public UserAccount(UserAccountType userAccountType) {

        this.userAccountType = userAccountType;
        this.userProfiles = new HashMap<Long,UserProfile>();
        this.userProfilesAmount = this.userProfiles.size();
    }
    //endregion

    //region Getters & Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UserAccountType getUserAccountType() {
        return userAccountType;
    }

    public void setUserAccountType(UserAccountType userAccountType) {
        this.userAccountType = userAccountType;
    }

    public Map<Long, UserProfile> getUserProfiles() {
        return userProfiles;
    }

    public void setUserProfiles(Map<Long, UserProfile> userProfiles) {
        this.userProfiles = userProfiles;
    }

    public int getUserProfilesAmount() {
        return userProfilesAmount;
    }

    public void setUserProfilesAmount(int userProfilesAmount) {
        this.userProfilesAmount = userProfilesAmount;
    }

    //endregion

    //region Parsers
    public ObjectNode toJson(){

        ObjectMapper jsonMapper = new ObjectMapper();

        try {

            ObjectWriter objectWriter = new ObjectMapper().writer().withDefaultPrettyPrinter();
            String jsonString = objectWriter.writeValueAsString(this);
            JsonNode jsonNode = jsonMapper.readTree(jsonString);
            return (ObjectNode)jsonNode;

        } catch (Exception ex){

            return null;
        }

    }
    //endregion

    //region Business Methods
    public boolean addUserProfile(UserProfile userProfile){

        /*We should only be able to add a user profile that does not already have a valid id because it will be generated by JPA (avoids id clashes)
         *We must also ensure we know what type of user profile it is to treat it accordingly*/
        if((userProfile.getId() == null || userProfile.getId() < 0) && userProfile.getUserProfileType() != null && this.areProfilesLoaded())
        {
            this.userProfiles.put(userProfile.getId(),userProfile);
            this.userProfilesAmount = this.userProfiles.size();

            return true;
        }

        return false;
    }

    public boolean removeUserProfile(Long userProfileId){

        if(this.areProfilesLoaded())
        {
            int amountBeforeRemove = this.userProfiles.size();
            this.userProfiles.remove(userProfileId);
            int amountAfterRemove = this.userProfiles.size();

            if(amountBeforeRemove > amountAfterRemove)
            {
                this.userProfilesAmount = this.userProfiles.size();
                return true;
            }

            return false;
        }

        return false;
    }

    public UserProfile getUserProfile(Long userProfileId){

        if(this.areProfilesLoaded())
        {
            this.userProfiles.get(userProfileId);
        }

        return null;
    }

    public int updateFrom(UserAccount userAccountUpdates){

        int updatesAmount = 0;

        //update user profiles if they were loaded (we don't remove or add new profiles here we only take the existing user profiles into consideration)
        if(this.areProfilesLoaded())
        {
            //update existing user profiles that belong to this user account
            for(UserProfile userProfile : userAccountUpdates.getUserProfiles().values())
            {
                //Check that the id is valid
                if(userProfile.getId() > 0)
                {
                    //try find the existing corresponding user profile id
                    UserProfile existingUserProfile = this.userProfiles.get(userProfile.getId());

                    //we found it now lets update it and add it to the updated map
                    if(existingUserProfile != null)
                    {
                        updatesAmount = updatesAmount + existingUserProfile.updateFrom(userProfile);
                    }
                }

            }

        }

        return updatesAmount;
    }

    public boolean areProfilesLoaded(){

        if(this.userProfiles.size() == this.userProfilesAmount)
        {
            return true;
        }

        return false;
    }
    //endregion
}
